<?php

/*
 * Implement hook_init() 
 * $is_enabled - checks if the functionality is enabled/disabled
 * $message_type - it could be status|warning|error
 * $message_body - the body of the message
 */

function current_date_message_init() {
  $is_enabled = variable_get('cdm_is_enabled');
  
  if ($is_enabled) {
    $message_body = "Today is " . date('l, F j, Y');
    $message_type = variable_get('cdm_message_type');
    
    drupal_set_message($message_body, $message_type);    
  }
}

/*
 * Implement hook_menu()
 */

function current_date_message_menu() {
  $items['admin/config/current-date-message'] = array(
    'title' => 'Current Date Message',
    'description' => 'This is the settings page for the Current Date Message module',
    'page callback' => 'drupal_get_form',
    'access callback' => true,
    'page arguments' => array('current_date_message_form'),
    'type' => MENU_NORMAL_ITEM
    );
  
  return $items;
}

/*
 * Settings callback for Current Date Message
 */

function current_date_message_form($form){
  
  // Enable/disable the functionality
  $form['cdm_is_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable the module',
    '#default_value' => variable_get('cdm_is_enabled', 0)
  );
  
  // Select the type fo the message
  $form['cdm_message_type'] = array(
    '#type' => 'select',
    '#title' => 'Select the type of the message',
    '#options' => array(
      'status' => 'Status',
      'warning' => 'Warning',
      'error' => 'Error'
    ),
    '#default_value' => variable_get('cdm_message_type', 'status')
  );
  
  return system_settings_form($form);
}